// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auctions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const checkUserParticipation = `-- name: CheckUserParticipation :one
SELECT EXISTS(SELECT 1
              FROM auction_participants
              WHERE auction_id = $1
                AND user_id = $2) AS "has_participated"
`

type CheckUserParticipationParams struct {
	AuctionID uuid.UUID `json:"auction_id"`
	UserID    string    `json:"user_id"`
}

func (q *Queries) CheckUserParticipation(ctx context.Context, arg CheckUserParticipationParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserParticipation, arg.AuctionID, arg.UserID)
	var has_participated bool
	err := row.Scan(&has_participated)
	return has_participated, err
}

const countSellerActiveAuctions = `-- name: CountSellerActiveAuctions :one
SELECT COUNT(*)
FROM auctions
WHERE seller_id = $1
  AND status IN ('scheduled', 'active')
`

func (q *Queries) CountSellerActiveAuctions(ctx context.Context, sellerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSellerActiveAuctions, sellerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuction = `-- name: CreateAuction :one
INSERT INTO auctions (id,
                      request_id,
                      gundam_id,
                      seller_id,
                      gundam_snapshot,
                      starting_price,
                      bid_increment,
                      buy_now_price,
                      current_price,
                      deposit_rate,
                      deposit_amount,
                      start_time,
                      end_time)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING id, request_id, gundam_id, seller_id, gundam_snapshot, starting_price, bid_increment, winning_bid_id, buy_now_price, start_time, end_time, actual_end_time, status, current_price, deposit_rate, deposit_amount, total_participants, total_bids, winner_payment_deadline, order_id, canceled_by, canceled_reason, created_at, updated_at
`

type CreateAuctionParams struct {
	ID             uuid.UUID       `json:"id"`
	RequestID      *uuid.UUID      `json:"request_id"`
	GundamID       *int64          `json:"gundam_id"`
	SellerID       string          `json:"seller_id"`
	GundamSnapshot GundamSnapshot  `json:"gundam_snapshot"`
	StartingPrice  int64           `json:"starting_price"`
	BidIncrement   int64           `json:"bid_increment"`
	BuyNowPrice    *int64          `json:"buy_now_price"`
	CurrentPrice   int64           `json:"current_price"`
	DepositRate    decimal.Decimal `json:"deposit_rate"`
	DepositAmount  int64           `json:"deposit_amount"`
	StartTime      time.Time       `json:"start_time"`
	EndTime        time.Time       `json:"end_time"`
}

func (q *Queries) CreateAuction(ctx context.Context, arg CreateAuctionParams) (Auction, error) {
	row := q.db.QueryRow(ctx, createAuction,
		arg.ID,
		arg.RequestID,
		arg.GundamID,
		arg.SellerID,
		arg.GundamSnapshot,
		arg.StartingPrice,
		arg.BidIncrement,
		arg.BuyNowPrice,
		arg.CurrentPrice,
		arg.DepositRate,
		arg.DepositAmount,
		arg.StartTime,
		arg.EndTime,
	)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.GundamID,
		&i.SellerID,
		&i.GundamSnapshot,
		&i.StartingPrice,
		&i.BidIncrement,
		&i.WinningBidID,
		&i.BuyNowPrice,
		&i.StartTime,
		&i.EndTime,
		&i.ActualEndTime,
		&i.Status,
		&i.CurrentPrice,
		&i.DepositRate,
		&i.DepositAmount,
		&i.TotalParticipants,
		&i.TotalBids,
		&i.WinnerPaymentDeadline,
		&i.OrderID,
		&i.CanceledBy,
		&i.CanceledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuctionByID = `-- name: GetAuctionByID :one
SELECT id, request_id, gundam_id, seller_id, gundam_snapshot, starting_price, bid_increment, winning_bid_id, buy_now_price, start_time, end_time, actual_end_time, status, current_price, deposit_rate, deposit_amount, total_participants, total_bids, winner_payment_deadline, order_id, canceled_by, canceled_reason, created_at, updated_at
FROM auctions
WHERE id = $1
`

func (q *Queries) GetAuctionByID(ctx context.Context, id uuid.UUID) (Auction, error) {
	row := q.db.QueryRow(ctx, getAuctionByID, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.GundamID,
		&i.SellerID,
		&i.GundamSnapshot,
		&i.StartingPrice,
		&i.BidIncrement,
		&i.WinningBidID,
		&i.BuyNowPrice,
		&i.StartTime,
		&i.EndTime,
		&i.ActualEndTime,
		&i.Status,
		&i.CurrentPrice,
		&i.DepositRate,
		&i.DepositAmount,
		&i.TotalParticipants,
		&i.TotalBids,
		&i.WinnerPaymentDeadline,
		&i.OrderID,
		&i.CanceledBy,
		&i.CanceledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuctionByIDForUpdate = `-- name: GetAuctionByIDForUpdate :one
SELECT id, request_id, gundam_id, seller_id, gundam_snapshot, starting_price, bid_increment, winning_bid_id, buy_now_price, start_time, end_time, actual_end_time, status, current_price, deposit_rate, deposit_amount, total_participants, total_bids, winner_payment_deadline, order_id, canceled_by, canceled_reason, created_at, updated_at
FROM auctions
WHERE id = $1
    FOR UPDATE
`

func (q *Queries) GetAuctionByIDForUpdate(ctx context.Context, id uuid.UUID) (Auction, error) {
	row := q.db.QueryRow(ctx, getAuctionByIDForUpdate, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.GundamID,
		&i.SellerID,
		&i.GundamSnapshot,
		&i.StartingPrice,
		&i.BidIncrement,
		&i.WinningBidID,
		&i.BuyNowPrice,
		&i.StartTime,
		&i.EndTime,
		&i.ActualEndTime,
		&i.Status,
		&i.CurrentPrice,
		&i.DepositRate,
		&i.DepositAmount,
		&i.TotalParticipants,
		&i.TotalBids,
		&i.WinnerPaymentDeadline,
		&i.OrderID,
		&i.CanceledBy,
		&i.CanceledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuctionByOrderID = `-- name: GetAuctionByOrderID :one
SELECT id, request_id, gundam_id, seller_id, gundam_snapshot, starting_price, bid_increment, winning_bid_id, buy_now_price, start_time, end_time, actual_end_time, status, current_price, deposit_rate, deposit_amount, total_participants, total_bids, winner_payment_deadline, order_id, canceled_by, canceled_reason, created_at, updated_at
FROM auctions
WHERE order_id = $1
`

func (q *Queries) GetAuctionByOrderID(ctx context.Context, orderID *uuid.UUID) (Auction, error) {
	row := q.db.QueryRow(ctx, getAuctionByOrderID, orderID)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.GundamID,
		&i.SellerID,
		&i.GundamSnapshot,
		&i.StartingPrice,
		&i.BidIncrement,
		&i.WinningBidID,
		&i.BuyNowPrice,
		&i.StartTime,
		&i.EndTime,
		&i.ActualEndTime,
		&i.Status,
		&i.CurrentPrice,
		&i.DepositRate,
		&i.DepositAmount,
		&i.TotalParticipants,
		&i.TotalBids,
		&i.WinnerPaymentDeadline,
		&i.OrderID,
		&i.CanceledBy,
		&i.CanceledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAuctionParticipants = `-- name: IncrementAuctionParticipants :one
UPDATE auctions
SET total_participants = total_participants + 1
WHERE id = $1 RETURNING id, request_id, gundam_id, seller_id, gundam_snapshot, starting_price, bid_increment, winning_bid_id, buy_now_price, start_time, end_time, actual_end_time, status, current_price, deposit_rate, deposit_amount, total_participants, total_bids, winner_payment_deadline, order_id, canceled_by, canceled_reason, created_at, updated_at
`

func (q *Queries) IncrementAuctionParticipants(ctx context.Context, id uuid.UUID) (Auction, error) {
	row := q.db.QueryRow(ctx, incrementAuctionParticipants, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.GundamID,
		&i.SellerID,
		&i.GundamSnapshot,
		&i.StartingPrice,
		&i.BidIncrement,
		&i.WinningBidID,
		&i.BuyNowPrice,
		&i.StartTime,
		&i.EndTime,
		&i.ActualEndTime,
		&i.Status,
		&i.CurrentPrice,
		&i.DepositRate,
		&i.DepositAmount,
		&i.TotalParticipants,
		&i.TotalBids,
		&i.WinnerPaymentDeadline,
		&i.OrderID,
		&i.CanceledBy,
		&i.CanceledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAuctionTotalBids = `-- name: IncrementAuctionTotalBids :one
UPDATE auctions
SET total_bids = total_bids + 1
WHERE id = $1 RETURNING id, request_id, gundam_id, seller_id, gundam_snapshot, starting_price, bid_increment, winning_bid_id, buy_now_price, start_time, end_time, actual_end_time, status, current_price, deposit_rate, deposit_amount, total_participants, total_bids, winner_payment_deadline, order_id, canceled_by, canceled_reason, created_at, updated_at
`

func (q *Queries) IncrementAuctionTotalBids(ctx context.Context, id uuid.UUID) (Auction, error) {
	row := q.db.QueryRow(ctx, incrementAuctionTotalBids, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.GundamID,
		&i.SellerID,
		&i.GundamSnapshot,
		&i.StartingPrice,
		&i.BidIncrement,
		&i.WinningBidID,
		&i.BuyNowPrice,
		&i.StartTime,
		&i.EndTime,
		&i.ActualEndTime,
		&i.Status,
		&i.CurrentPrice,
		&i.DepositRate,
		&i.DepositAmount,
		&i.TotalParticipants,
		&i.TotalBids,
		&i.WinnerPaymentDeadline,
		&i.OrderID,
		&i.CanceledBy,
		&i.CanceledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuctions = `-- name: ListAuctions :many
SELECT id, request_id, gundam_id, seller_id, gundam_snapshot, starting_price, bid_increment, winning_bid_id, buy_now_price, start_time, end_time, actual_end_time, status, current_price, deposit_rate, deposit_amount, total_participants, total_bids, winner_payment_deadline, order_id, canceled_by, canceled_reason, created_at, updated_at
FROM auctions
WHERE status = COALESCE($1, status)
ORDER BY CASE status
             -- Phiên đang diễn ra: ưu tiên theo thời gian kết thúc gần nhất
             WHEN 'active' THEN EXTRACT(EPOCH FROM end_time)
             -- Phiên sắp diễn ra: ưu tiên theo thời gian bắt đầu sớm nhất
             WHEN 'scheduled' THEN EXTRACT(EPOCH FROM start_time)
             -- Các trạng thái khác: sắp xếp theo thời gian tạo mới nhất
             ELSE EXTRACT(EPOCH FROM created_at) * -1
             END ASC,
         created_at DESC
`

func (q *Queries) ListAuctions(ctx context.Context, status NullAuctionStatus) ([]Auction, error) {
	rows, err := q.db.Query(ctx, listAuctions, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Auction{}
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.GundamID,
			&i.SellerID,
			&i.GundamSnapshot,
			&i.StartingPrice,
			&i.BidIncrement,
			&i.WinningBidID,
			&i.BuyNowPrice,
			&i.StartTime,
			&i.EndTime,
			&i.ActualEndTime,
			&i.Status,
			&i.CurrentPrice,
			&i.DepositRate,
			&i.DepositAmount,
			&i.TotalParticipants,
			&i.TotalBids,
			&i.WinnerPaymentDeadline,
			&i.OrderID,
			&i.CanceledBy,
			&i.CanceledReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerAuctions = `-- name: ListSellerAuctions :many
SELECT id, request_id, gundam_id, seller_id, gundam_snapshot, starting_price, bid_increment, winning_bid_id, buy_now_price, start_time, end_time, actual_end_time, status, current_price, deposit_rate, deposit_amount, total_participants, total_bids, winner_payment_deadline, order_id, canceled_by, canceled_reason, created_at, updated_at
FROM auctions
WHERE seller_id = $1
  AND status = COALESCE($2, status)
ORDER BY CASE status
             -- Phiên đang diễn ra: ưu tiên theo thời gian kết thúc gần nhất
             WHEN 'active' THEN EXTRACT(EPOCH FROM end_time)
             -- Phiên sắp diễn ra: ưu tiên theo thời gian bắt đầu sớm nhất
             WHEN 'scheduled' THEN EXTRACT(EPOCH FROM start_time)
             -- Các trạng thái khác: sắp xếp theo thời gian tạo mới nhất
             ELSE EXTRACT(EPOCH FROM created_at) * -1
             END ASC,
         created_at DESC
`

type ListSellerAuctionsParams struct {
	SellerID string            `json:"seller_id"`
	Status   NullAuctionStatus `json:"status"`
}

func (q *Queries) ListSellerAuctions(ctx context.Context, arg ListSellerAuctionsParams) ([]Auction, error) {
	rows, err := q.db.Query(ctx, listSellerAuctions, arg.SellerID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Auction{}
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.GundamID,
			&i.SellerID,
			&i.GundamSnapshot,
			&i.StartingPrice,
			&i.BidIncrement,
			&i.WinningBidID,
			&i.BuyNowPrice,
			&i.StartTime,
			&i.EndTime,
			&i.ActualEndTime,
			&i.Status,
			&i.CurrentPrice,
			&i.DepositRate,
			&i.DepositAmount,
			&i.TotalParticipants,
			&i.TotalBids,
			&i.WinnerPaymentDeadline,
			&i.OrderID,
			&i.CanceledBy,
			&i.CanceledReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserParticipatedAuctions = `-- name: ListUserParticipatedAuctions :many
SELECT a.id, a.request_id, a.gundam_id, a.seller_id, a.gundam_snapshot, a.starting_price, a.bid_increment, a.winning_bid_id, a.buy_now_price, a.start_time, a.end_time, a.actual_end_time, a.status, a.current_price, a.deposit_rate, a.deposit_amount, a.total_participants, a.total_bids, a.winner_payment_deadline, a.order_id, a.canceled_by, a.canceled_reason, a.created_at, a.updated_at,
       ap.id, ap.auction_id, ap.user_id, ap.deposit_amount, ap.deposit_entry_id, ap.is_refunded, ap.created_at, ap.updated_at
FROM auctions a
         JOIN auction_participants ap ON a.id = ap.auction_id
WHERE ap.user_id = $1
ORDER BY CASE a.status
             -- Phiên đang diễn ra: ưu tiên theo thời gian kết thúc gần nhất
             WHEN 'active' THEN EXTRACT(EPOCH FROM a.end_time)
             -- Phiên sắp diễn ra: ưu tiên theo thời gian bắt đầu sớm nhất
             WHEN 'scheduled' THEN EXTRACT(EPOCH FROM a.start_time)
             -- Các trạng thái khác: sắp xếp theo thời gian tạo mới nhất
             ELSE EXTRACT(EPOCH FROM a.created_at) * -1
             END
    ASC,
         a.created_at DESC
`

type ListUserParticipatedAuctionsRow struct {
	Auction            Auction            `json:"auction"`
	AuctionParticipant AuctionParticipant `json:"auction_participant"`
}

func (q *Queries) ListUserParticipatedAuctions(ctx context.Context, userID string) ([]ListUserParticipatedAuctionsRow, error) {
	rows, err := q.db.Query(ctx, listUserParticipatedAuctions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserParticipatedAuctionsRow{}
	for rows.Next() {
		var i ListUserParticipatedAuctionsRow
		if err := rows.Scan(
			&i.Auction.ID,
			&i.Auction.RequestID,
			&i.Auction.GundamID,
			&i.Auction.SellerID,
			&i.Auction.GundamSnapshot,
			&i.Auction.StartingPrice,
			&i.Auction.BidIncrement,
			&i.Auction.WinningBidID,
			&i.Auction.BuyNowPrice,
			&i.Auction.StartTime,
			&i.Auction.EndTime,
			&i.Auction.ActualEndTime,
			&i.Auction.Status,
			&i.Auction.CurrentPrice,
			&i.Auction.DepositRate,
			&i.Auction.DepositAmount,
			&i.Auction.TotalParticipants,
			&i.Auction.TotalBids,
			&i.Auction.WinnerPaymentDeadline,
			&i.Auction.OrderID,
			&i.Auction.CanceledBy,
			&i.Auction.CanceledReason,
			&i.Auction.CreatedAt,
			&i.Auction.UpdatedAt,
			&i.AuctionParticipant.ID,
			&i.AuctionParticipant.AuctionID,
			&i.AuctionParticipant.UserID,
			&i.AuctionParticipant.DepositAmount,
			&i.AuctionParticipant.DepositEntryID,
			&i.AuctionParticipant.IsRefunded,
			&i.AuctionParticipant.CreatedAt,
			&i.AuctionParticipant.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuction = `-- name: UpdateAuction :one
UPDATE auctions
SET status                  = COALESCE($2, status),
    current_price           = COALESCE($3, current_price),
    winning_bid_id          = COALESCE($4, winning_bid_id),
    winner_payment_deadline = COALESCE($5, winner_payment_deadline),
    actual_end_time         = COALESCE($6, actual_end_time),
    order_id                = COALESCE($7, order_id),
    updated_at              = now()
WHERE id = $1 RETURNING id, request_id, gundam_id, seller_id, gundam_snapshot, starting_price, bid_increment, winning_bid_id, buy_now_price, start_time, end_time, actual_end_time, status, current_price, deposit_rate, deposit_amount, total_participants, total_bids, winner_payment_deadline, order_id, canceled_by, canceled_reason, created_at, updated_at
`

type UpdateAuctionParams struct {
	ID                    uuid.UUID         `json:"id"`
	Status                NullAuctionStatus `json:"status"`
	CurrentPrice          *int64            `json:"current_price"`
	WinningBidID          *uuid.UUID        `json:"winning_bid_id"`
	WinnerPaymentDeadline *time.Time        `json:"winner_payment_deadline"`
	ActualEndTime         *time.Time        `json:"actual_end_time"`
	OrderID               *uuid.UUID        `json:"order_id"`
}

func (q *Queries) UpdateAuction(ctx context.Context, arg UpdateAuctionParams) (Auction, error) {
	row := q.db.QueryRow(ctx, updateAuction,
		arg.ID,
		arg.Status,
		arg.CurrentPrice,
		arg.WinningBidID,
		arg.WinnerPaymentDeadline,
		arg.ActualEndTime,
		arg.OrderID,
	)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.GundamID,
		&i.SellerID,
		&i.GundamSnapshot,
		&i.StartingPrice,
		&i.BidIncrement,
		&i.WinningBidID,
		&i.BuyNowPrice,
		&i.StartTime,
		&i.EndTime,
		&i.ActualEndTime,
		&i.Status,
		&i.CurrentPrice,
		&i.DepositRate,
		&i.DepositAmount,
		&i.TotalParticipants,
		&i.TotalBids,
		&i.WinnerPaymentDeadline,
		&i.OrderID,
		&i.CanceledBy,
		&i.CanceledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
