// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auctions.sql

package db

import (
	"context"
)

const countSellerActiveAuctions = `-- name: CountSellerActiveAuctions :one
SELECT COUNT(*)
FROM auctions
WHERE seller_id = $1
  AND status IN ('scheduled', 'active')
`

func (q *Queries) CountSellerActiveAuctions(ctx context.Context, sellerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSellerActiveAuctions, sellerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
