// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: grades.sql

package db

import (
	"context"
)

const getGradeByID = `-- name: GetGradeByID :one
SELECT id, name, display_name, slug, created_at
FROM gundam_grades
WHERE id = $1
`

func (q *Queries) GetGradeByID(ctx context.Context, id int64) (GundamGrade, error) {
	row := q.db.QueryRow(ctx, getGradeByID, id)
	var i GundamGrade
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
