// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: gundam_images.sql

package db

import (
	"context"
)

const createGundamImage = `-- name: CreateGundamImage :exec
INSERT INTO gundam_images (gundam_id, url, is_primary)
VALUES ($1, $2, $3)
`

type CreateGundamImageParams struct {
	GundamID  int64  `json:"gundam_id"`
	Url       string `json:"url"`
	IsPrimary bool   `json:"is_primary"`
}

func (q *Queries) CreateGundamImage(ctx context.Context, arg CreateGundamImageParams) error {
	_, err := q.db.Exec(ctx, createGundamImage, arg.GundamID, arg.Url, arg.IsPrimary)
	return err
}
