// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: gundam_grades.sql

package db

import (
	"context"
)

const listGundamGrades = `-- name: ListGundamGrades :many
SELECT id, name, display_name, slug, created_at
FROM gundam_grades
`

func (q *Queries) ListGundamGrades(ctx context.Context) ([]GundamGrade, error) {
	rows, err := q.db.Query(ctx, listGundamGrades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GundamGrade{}
	for rows.Next() {
		var i GundamGrade
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
