// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: gundams.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGundam = `-- name: CreateGundam :one
INSERT INTO gundams (owner_id, name, grade_id, condition, manufacturer, scale, description, price, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, owner_id, name, grade_id, condition, manufacturer, scale, description, price, status, created_at, updated_at, deleted_at
`

type CreateGundamParams struct {
	OwnerID      string          `json:"owner_id"`
	Name         string          `json:"name"`
	GradeID      int64           `json:"grade_id"`
	Condition    GundamCondition `json:"condition"`
	Manufacturer string          `json:"manufacturer"`
	Scale        GundamScale     `json:"scale"`
	Description  string          `json:"description"`
	Price        int64           `json:"price"`
	Status       GundamStatus    `json:"status"`
}

func (q *Queries) CreateGundam(ctx context.Context, arg CreateGundamParams) (Gundam, error) {
	row := q.db.QueryRow(ctx, createGundam,
		arg.OwnerID,
		arg.Name,
		arg.GradeID,
		arg.Condition,
		arg.Manufacturer,
		arg.Scale,
		arg.Description,
		arg.Price,
		arg.Status,
	)
	var i Gundam
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.GradeID,
		&i.Condition,
		&i.Manufacturer,
		&i.Scale,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listGundamsWithFilters = `-- name: ListGundamsWithFilters :many
SELECT g.id,
       g.name,
       g.description,
       g.price,
       g.created_at,
       g.updated_at,
       gr.id         as grade_id,
       gr.name       as grade_name,
       gr.slug       as grade_slug
FROM gundams g
         JOIN gundam_grades gr ON g.grade_id = gr.id
WHERE CASE
          WHEN $1::text IS NULL THEN true
        ELSE gr.slug = $1::text
END
ORDER BY g.created_at DESC
`

type ListGundamsWithFiltersRow struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Price       int64     `json:"price"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	GradeID     int64     `json:"grade_id"`
	GradeName   string    `json:"grade_name"`
	GradeSlug   string    `json:"grade_slug"`
}

func (q *Queries) ListGundamsWithFilters(ctx context.Context, gradeSlug pgtype.Text) ([]ListGundamsWithFiltersRow, error) {
	rows, err := q.db.Query(ctx, listGundamsWithFilters, gradeSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGundamsWithFiltersRow{}
	for rows.Next() {
		var i ListGundamsWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GradeID,
			&i.GradeName,
			&i.GradeSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
