// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: moderators.sql

package db

import (
	"context"
)

const getModPendingAuctionRequestsCount = `-- name: GetModPendingAuctionRequestsCount :one
SELECT COUNT(*) as count
FROM auction_requests
WHERE status = 'pending'
`

// Metric 1: Yêu cầu đấu giá chờ moderator duyệt (bảng auction_requests)
func (q *Queries) GetModPendingAuctionRequestsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getModPendingAuctionRequestsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
