// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                  string      `json:"id"`
	Name                string      `json:"name"`
	HashedPassword      pgtype.Text `json:"-"`
	Email               string      `json:"email"`
	EmailVerified       bool        `json:"email_verified"`
	Role                string      `json:"role"`
	Avatar              pgtype.Text `json:"avatar"`
	CreatedAt           time.Time   `json:"created_at"`
	PhoneNumber         pgtype.Text `json:"phone_number"`
	PhoneNumberVerified bool        `json:"phone_number_verified"`
}
