// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: order_items.sql

package db

import (
	"context"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id,
                         gundam_id,
                         price)
VALUES ($1, $2, $3) RETURNING id, order_id, gundam_id, quantity, price, created_at
`

type CreateOrderItemParams struct {
	OrderID  string `json:"order_id"`
	GundamID int64  `json:"gundam_id"`
	Price    int64  `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem, arg.OrderID, arg.GundamID, arg.Price)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.GundamID,
		&i.Quantity,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}
