// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: order_transactions.sql

package db

import (
	"context"
)

const createOrderTransaction = `-- name: CreateOrderTransaction :one
INSERT INTO order_transactions (order_id,
                                amount,
                                status,
                                buyer_entry_id)
VALUES ($1, $2, $3, $4) RETURNING id, order_id, amount, status, buyer_entry_id, seller_entry_id, created_at, updated_at
`

type CreateOrderTransactionParams struct {
	OrderID      string                 `json:"order_id"`
	Amount       int64                  `json:"amount"`
	Status       OrderTransactionStatus `json:"status"`
	BuyerEntryID int64                  `json:"buyer_entry_id"`
}

func (q *Queries) CreateOrderTransaction(ctx context.Context, arg CreateOrderTransactionParams) (OrderTransaction, error) {
	row := q.db.QueryRow(ctx, createOrderTransaction,
		arg.OrderID,
		arg.Amount,
		arg.Status,
		arg.BuyerEntryID,
	)
	var i OrderTransaction
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Status,
		&i.BuyerEntryID,
		&i.SellerEntryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
