// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: payment_transactions.sql

package db

import (
	"context"
)

const createPaymentTransaction = `-- name: CreatePaymentTransaction :one
INSERT INTO payment_transactions (id,
                                  user_id,
                                  amount,
                                  provider,
                                  provider_transaction_id,
                                  status,
                                  metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, amount, transaction_type, provider, provider_transaction_id, status, metadata, created_at, updated_at
`

type CreatePaymentTransactionParams struct {
	ID                    int64                      `json:"id"`
	UserID                string                     `json:"user_id"`
	Amount                int64                      `json:"amount"`
	Provider              PaymentTransactionProvider `json:"provider"`
	ProviderTransactionID string                     `json:"provider_transaction_id"`
	Status                PaymentTransactionStatus   `json:"status"`
	Metadata              []byte                     `json:"metadata"`
}

func (q *Queries) CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, createPaymentTransaction,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.Provider,
		arg.ProviderTransactionID,
		arg.Status,
		arg.Metadata,
	)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.TransactionType,
		&i.Provider,
		&i.ProviderTransactionID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
