// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCartItem(ctx context.Context, arg AddCartItemParams) (AddCartItemRow, error)
	CreateAccessory(ctx context.Context, arg CreateAccessoryParams) error
	CreateGundam(ctx context.Context, arg CreateGundamParams) (Gundam, error)
	CreateGundamAccessory(ctx context.Context, arg CreateGundamAccessoryParams) (GundamAccessory, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserAddress(ctx context.Context, arg CreateUserAddressParams) (UserAddress, error)
	CreateUserWithGoogleAccount(ctx context.Context, arg CreateUserWithGoogleAccountParams) (User, error)
	DeleteUserAddress(ctx context.Context, arg DeleteUserAddressParams) error
	GetCartByUserID(ctx context.Context, userID string) (int64, error)
	GetGundamAccessories(ctx context.Context, gundamID int64) ([]GundamAccessory, error)
	GetGundamBySlug(ctx context.Context, slug string) (GetGundamBySlugRow, error)
	GetOrCreateCartIfNotExists(ctx context.Context, userID string) (int64, error)
	GetSellerByID(ctx context.Context, id string) (User, error)
	GetUserAddressForUpdate(ctx context.Context, arg GetUserAddressForUpdateParams) (UserAddress, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByPhoneNumber(ctx context.Context, phoneNumber pgtype.Text) (User, error)
	GetUserPickupAddress(ctx context.Context, userID string) (UserAddress, error)
	ListCartItemsWithDetails(ctx context.Context, cartID int64) ([]ListCartItemsWithDetailsRow, error)
	ListGundamGrades(ctx context.Context) ([]GundamGrade, error)
	ListGundamsBySellerID(ctx context.Context, arg ListGundamsBySellerIDParams) ([]ListGundamsBySellerIDRow, error)
	ListGundamsWithFilters(ctx context.Context, gradeSlug pgtype.Text) ([]ListGundamsWithFiltersRow, error)
	ListUserAddresses(ctx context.Context, userID string) ([]UserAddress, error)
	RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error
	StoreGundamImageURL(ctx context.Context, arg StoreGundamImageURLParams) error
	UnsetPickupAddress(ctx context.Context, userID string) error
	UnsetPrimaryAddress(ctx context.Context, userID string) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) (UserAddress, error)
}

var _ Querier = (*Queries)(nil)
