// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (hashed_password, full_name, email, email_verified, phone_number, phone_number_verified, role,
                   avatar_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, full_name, hashed_password, email, email_verified, phone_number, phone_number_verified, role, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	HashedPassword      pgtype.Text `json:"-"`
	FullName            pgtype.Text `extensions:"x-nullable" json:"full_name"`
	Email               string      `json:"email"`
	EmailVerified       bool        `json:"email_verified"`
	PhoneNumber         pgtype.Text `extensions:"x-nullable" json:"phone_number"`
	PhoneNumberVerified bool        `json:"phone_number_verified"`
	Role                UserRole    `json:"role"`
	AvatarUrl           pgtype.Text `extensions:"x-nullable" json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.HashedPassword,
		arg.FullName,
		arg.Email,
		arg.EmailVerified,
		arg.PhoneNumber,
		arg.PhoneNumberVerified,
		arg.Role,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.HashedPassword,
		&i.Email,
		&i.EmailVerified,
		&i.PhoneNumber,
		&i.PhoneNumberVerified,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserAddress = `-- name: CreateUserAddress :one
INSERT INTO user_addresses (user_id, full_name, phone_number, province_name, district_name, ghn_district_id, ward_name,
                            ghn_ward_code,
                            detail, is_primary, is_pickup_address)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, user_id, full_name, phone_number, province_name, district_name, ghn_district_id, ward_name, ghn_ward_code, detail, is_primary, is_pickup_address, created_at, updated_at
`

type CreateUserAddressParams struct {
	UserID          string `json:"user_id"`
	FullName        string `json:"full_name"`
	PhoneNumber     string `json:"phone_number"`
	ProvinceName    string `json:"province_name"`
	DistrictName    string `json:"district_name"`
	GhnDistrictID   int64  `json:"ghn_district_id"`
	WardName        string `json:"ward_name"`
	GhnWardCode     string `json:"ghn_ward_code"`
	Detail          string `json:"detail"`
	IsPrimary       bool   `json:"is_primary"`
	IsPickupAddress bool   `json:"is_pickup_address"`
}

func (q *Queries) CreateUserAddress(ctx context.Context, arg CreateUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, createUserAddress,
		arg.UserID,
		arg.FullName,
		arg.PhoneNumber,
		arg.ProvinceName,
		arg.DistrictName,
		arg.GhnDistrictID,
		arg.WardName,
		arg.GhnWardCode,
		arg.Detail,
		arg.IsPrimary,
		arg.IsPickupAddress,
	)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.PhoneNumber,
		&i.ProvinceName,
		&i.DistrictName,
		&i.GhnDistrictID,
		&i.WardName,
		&i.GhnWardCode,
		&i.Detail,
		&i.IsPrimary,
		&i.IsPickupAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserWithGoogleAccount = `-- name: CreateUserWithGoogleAccount :one
INSERT INTO users (id, full_name, email, email_verified, avatar_url)
VALUES ($1, $2, $3, $4, $5) RETURNING id, full_name, hashed_password, email, email_verified, phone_number, phone_number_verified, role, avatar_url, created_at, updated_at
`

type CreateUserWithGoogleAccountParams struct {
	ID            string      `json:"id"`
	FullName      pgtype.Text `extensions:"x-nullable" json:"full_name"`
	Email         string      `json:"email"`
	EmailVerified bool        `json:"email_verified"`
	AvatarUrl     pgtype.Text `extensions:"x-nullable" json:"avatar_url"`
}

func (q *Queries) CreateUserWithGoogleAccount(ctx context.Context, arg CreateUserWithGoogleAccountParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithGoogleAccount,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.EmailVerified,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.HashedPassword,
		&i.Email,
		&i.EmailVerified,
		&i.PhoneNumber,
		&i.PhoneNumberVerified,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAddresses = `-- name: GetUserAddresses :many
SELECT id, user_id, full_name, phone_number, province_name, district_name, ghn_district_id, ward_name, ghn_ward_code, detail, is_primary, is_pickup_address, created_at, updated_at
FROM user_addresses
WHERE user_id = $1
ORDER BY is_primary DESC, created_at DESC
`

func (q *Queries) GetUserAddresses(ctx context.Context, userID string) ([]UserAddress, error) {
	rows, err := q.db.Query(ctx, getUserAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAddress{}
	for rows.Next() {
		var i UserAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.PhoneNumber,
			&i.ProvinceName,
			&i.DistrictName,
			&i.GhnDistrictID,
			&i.WardName,
			&i.GhnWardCode,
			&i.Detail,
			&i.IsPrimary,
			&i.IsPickupAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, hashed_password, email, email_verified, phone_number, phone_number_verified, role, avatar_url, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.HashedPassword,
		&i.Email,
		&i.EmailVerified,
		&i.PhoneNumber,
		&i.PhoneNumberVerified,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, hashed_password, email, email_verified, phone_number, phone_number_verified, role, avatar_url, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.HashedPassword,
		&i.Email,
		&i.EmailVerified,
		&i.PhoneNumber,
		&i.PhoneNumberVerified,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id, full_name, hashed_password, email, email_verified, phone_number, phone_number_verified, role, avatar_url, created_at, updated_at
FROM users
WHERE phone_number = $1
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.HashedPassword,
		&i.Email,
		&i.EmailVerified,
		&i.PhoneNumber,
		&i.PhoneNumberVerified,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unsetPickupAddress = `-- name: UnsetPickupAddress :exec
UPDATE user_addresses
SET is_pickup_address = false
WHERE user_id = $1
  AND is_pickup_address = true
`

func (q *Queries) UnsetPickupAddress(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, unsetPickupAddress, userID)
	return err
}

const unsetPrimaryAddress = `-- name: UnsetPrimaryAddress :exec
UPDATE user_addresses
SET is_primary = false
WHERE user_id = $1
  AND is_primary = true
`

func (q *Queries) UnsetPrimaryAddress(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, unsetPrimaryAddress, userID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET full_name    = COALESCE($1, full_name),
    avatar_url   = COALESCE($2, avatar_url),
    phone_number = COALESCE($3, phone_number),
    updated_at   = now()
WHERE id = $4 RETURNING id, full_name, hashed_password, email, email_verified, phone_number, phone_number_verified, role, avatar_url, created_at, updated_at
`

type UpdateUserParams struct {
	FullName    pgtype.Text `extensions:"x-nullable" json:"full_name"`
	AvatarUrl   pgtype.Text `extensions:"x-nullable" json:"avatar_url"`
	PhoneNumber pgtype.Text `extensions:"x-nullable" json:"phone_number"`
	UserID      string      `json:"user_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FullName,
		arg.AvatarUrl,
		arg.PhoneNumber,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.HashedPassword,
		&i.Email,
		&i.EmailVerified,
		&i.PhoneNumber,
		&i.PhoneNumberVerified,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
