// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_subscriptions.sql

package db

import (
	"context"
)

const createTrialSubscription = `-- name: CreateTrialSubscription :exec
WITH trial_plan AS (SELECT id
                    FROM subscription_plans
                    WHERE name = 'GÓI DÙNG THỬ' LIMIT 1
    )
INSERT
INTO user_subscriptions (user_id,
                         plan_id,
                         start_date,
                         end_date,
                         is_active)
VALUES (
    $1, (SELECT id FROM trial_plan), now(), NULL, true
    )
`

func (q *Queries) CreateTrialSubscription(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, createTrialSubscription, userID)
	return err
}
