// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: wallets.sql

package db

import (
	"context"
)

const createWallet = `-- name: CreateWallet :exec
INSERT INTO wallets (user_id)
VALUES ($1)
`

func (q *Queries) CreateWallet(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, createWallet, userID)
	return err
}
